import type { Vessel } from './types'

export const MOCK_VESSELS: Vessel[] = [
  {
    id: '1',
    vessel_name: 'MV API SHIRIN',
    dwt: 56556,
    grt: 31200,
    nrt: 18900,
    built_year: 2012,
    flag: 'Panama',
    loa: 189.9,
    beam: 32.26,
    grain_capacity: 71200,
    crane_details: '4 x 30T cranes',
    speed_laden_knots: 12.5,
    speed_ballast_knots: 13.0,
    consumption_laden_vlsfo: 22.5,
    consumption_ballast_vlsfo: 19.0,
    port_consumption_working_vlsfo: 3.5,
    port_consumption_idle_vlsfo: 1.2,
    open_port: 'Mumbai',
    open_date: '2026-03-22',
    last_5_cargoes: 'Coal, Iron Ore, Fertilizer, Coal, Grain',
    owner_manager: 'Unknown Sender',
    vetting_status: 'SIRE Inspected',
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-001',
    first_seen_at: '2026-03-20T10:00:00Z',
    last_seen_at: '2026-03-22T08:30:00Z',
    region: 'WCI',
    vessel_type: 'Supramax',
  },
  {
    id: '2',
    vessel_name: 'MV ERIETTA',
    dwt: 61166,
    grt: 34500,
    nrt: 21000,
    built_year: 2015,
    flag: 'Marshall Islands',
    loa: 199.9,
    beam: 32.26,
    grain_capacity: 76000,
    crane_details: '4 x 35T cranes',
    speed_laden_knots: 13.0,
    speed_ballast_knots: 13.5,
    consumption_laden_vlsfo: 24.0,
    consumption_ballast_vlsfo: 20.5,
    port_consumption_working_vlsfo: 3.8,
    port_consumption_idle_vlsfo: 1.4,
    open_port: 'Kandla',
    open_date: '2026-03-22',
    last_5_cargoes: 'Grain, Coal, Fertilizer, Iron Ore, Coal',
    owner_manager: 'Unknown Sender',
    vetting_status: 'CDI Inspected',
    scrubber_fitted: true,
    special_features: 'Scrubber fitted',
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-002',
    first_seen_at: '2026-03-21T09:00:00Z',
    last_seen_at: '2026-03-22T07:45:00Z',
    region: 'WCI',
    vessel_type: 'Ultramax',
  },
  {
    id: '3',
    vessel_name: 'MV OCEAN ARIEL',
    dwt: 42965,
    grt: 24800,
    nrt: 15200,
    built_year: 2025,
    flag: 'Liberia',
    loa: 179.9,
    beam: 30.0,
    grain_capacity: 53000,
    crane_details: '4 x 25T cranes',
    speed_laden_knots: 12.0,
    speed_ballast_knots: 12.5,
    consumption_laden_vlsfo: 18.5,
    consumption_ballast_vlsfo: 15.5,
    port_consumption_working_vlsfo: 3.0,
    port_consumption_idle_vlsfo: 1.0,
    open_port: 'Mundra',
    open_date: '2026-03-22',
    last_5_cargoes: 'Coal, Fertilizer, Coal, Grain, Coal',
    owner_manager: 'Aryacorp Pvt. Ltd.',
    vetting_status: null,
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-003',
    first_seen_at: '2026-03-22T11:00:00Z',
    last_seen_at: '2026-03-22T11:00:00Z',
    region: 'WCI',
    vessel_type: 'Handymax',
  },
  {
    id: '4',
    vessel_name: 'MV PVT TOPAZ',
    dwt: 57318,
    grt: 32100,
    nrt: 19500,
    built_year: 2009,
    flag: 'Hong Kong',
    loa: 189.9,
    beam: 32.26,
    grain_capacity: 71800,
    crane_details: '4 x 30T cranes',
    speed_laden_knots: 12.0,
    speed_ballast_knots: 12.5,
    consumption_laden_vlsfo: 23.0,
    consumption_ballast_vlsfo: 19.5,
    port_consumption_working_vlsfo: 3.5,
    port_consumption_idle_vlsfo: 1.3,
    open_port: 'Kandla',
    open_date: '2026-03-22',
    last_5_cargoes: 'Coal, Iron Ore, Grain, Coal, Fertilizer',
    owner_manager: 'Exodus Chartering Services',
    vetting_status: 'SIRE Inspected',
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'whatsapp',
    source_identifier: 'wa-001',
    first_seen_at: '2026-03-23T08:00:00Z',
    last_seen_at: '2026-03-23T08:00:00Z',
    region: 'WCI',
    vessel_type: 'Supramax',
  },
  {
    id: '5',
    vessel_name: 'MV STEFANOS D',
    dwt: 63515,
    grt: 35400,
    nrt: 21800,
    built_year: 2012,
    flag: 'Greece',
    loa: 199.9,
    beam: 32.26,
    grain_capacity: 79000,
    crane_details: '4 x 36T cranes',
    speed_laden_knots: 13.0,
    speed_ballast_knots: 13.5,
    consumption_laden_vlsfo: 25.0,
    consumption_ballast_vlsfo: 21.0,
    port_consumption_working_vlsfo: 4.0,
    port_consumption_idle_vlsfo: 1.5,
    open_port: 'Kandla',
    open_date: '2026-03-22',
    last_5_cargoes: 'Iron Ore, Coal, Grain, Coal, Iron Ore',
    owner_manager: 'IBC',
    vetting_status: 'CDI Inspected',
    scrubber_fitted: true,
    special_features: 'Scrubber fitted, IG system',
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-004',
    first_seen_at: '2026-03-22T14:00:00Z',
    last_seen_at: '2026-03-22T14:00:00Z',
    region: 'WCI',
    vessel_type: 'Ultramax',
  },
  {
    id: '6',
    vessel_name: 'MV V BRAVO',
    dwt: 56059,
    grt: 31100,
    nrt: 18800,
    built_year: 2010,
    flag: 'Panama',
    loa: 189.9,
    beam: 32.26,
    grain_capacity: 70500,
    crane_details: '4 x 30T cranes',
    speed_laden_knots: 12.5,
    speed_ballast_knots: 13.0,
    consumption_laden_vlsfo: 22.0,
    consumption_ballast_vlsfo: 18.5,
    port_consumption_working_vlsfo: 3.5,
    port_consumption_idle_vlsfo: 1.2,
    open_port: 'Mundra',
    open_date: '2026-03-23',
    last_5_cargoes: 'Fertilizer, Grain, Coal, Iron Ore, Coal',
    owner_manager: 'IBC',
    vetting_status: null,
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'teams',
    source_identifier: 'teams-001',
    first_seen_at: '2026-03-23T09:30:00Z',
    last_seen_at: '2026-03-23T09:30:00Z',
    region: 'WCI',
    vessel_type: 'Supramax',
  },
  {
    id: '7',
    vessel_name: 'MV XING LUO 88',
    dwt: 57173,
    grt: 31900,
    nrt: 19300,
    built_year: 2010,
    flag: 'Hong Kong',
    loa: 189.9,
    beam: 32.26,
    grain_capacity: 71200,
    crane_details: '4 x 30T cranes',
    speed_laden_knots: 12.5,
    speed_ballast_knots: 13.0,
    consumption_laden_vlsfo: 22.5,
    consumption_ballast_vlsfo: 19.0,
    port_consumption_working_vlsfo: 3.5,
    port_consumption_idle_vlsfo: 1.2,
    open_port: 'Mundra',
    open_date: '2026-03-22',
    last_5_cargoes: 'Coal, Coal, Iron Ore, Coal, Grain',
    owner_manager: 'JACK',
    vetting_status: 'SIRE Inspected',
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'whatsapp',
    source_identifier: 'wa-002',
    first_seen_at: '2026-03-22T16:00:00Z',
    last_seen_at: '2026-03-22T16:00:00Z',
    region: 'WCI',
    vessel_type: 'Supramax',
  },
  {
    id: '8',
    vessel_name: 'MV CN MINJIANG',
    dwt: 50259,
    grt: 28900,
    nrt: 17500,
    built_year: 2001,
    flag: 'China',
    loa: 185.0,
    beam: 30.4,
    grain_capacity: 63000,
    crane_details: '4 x 25T cranes',
    speed_laden_knots: 11.5,
    speed_ballast_knots: 12.0,
    consumption_laden_vlsfo: 20.0,
    consumption_ballast_vlsfo: 17.0,
    port_consumption_working_vlsfo: 3.0,
    port_consumption_idle_vlsfo: 1.0,
    open_port: 'Karachi',
    open_date: '2026-03-23',
    last_5_cargoes: 'Coal, Iron Ore, Coal, Coal, Fertilizer',
    owner_manager: 'fixittheoffe.com',
    vetting_status: null,
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-005',
    first_seen_at: '2026-03-23T10:00:00Z',
    last_seen_at: '2026-03-23T10:00:00Z',
    region: 'AG',
    vessel_type: 'Supramax',
  },
  {
    id: '9',
    vessel_name: 'MV NEW MOMENTUM',
    dwt: 39042,
    grt: 22500,
    nrt: 13800,
    built_year: 2018,
    flag: 'Marshall Islands',
    loa: 172.0,
    beam: 28.0,
    grain_capacity: 48500,
    crane_details: '4 x 30T cranes',
    speed_laden_knots: 13.5,
    speed_ballast_knots: 14.0,
    consumption_laden_vlsfo: 17.0,
    consumption_ballast_vlsfo: 14.5,
    port_consumption_working_vlsfo: 2.8,
    port_consumption_idle_vlsfo: 0.9,
    open_port: 'Mumbai',
    open_date: '2026-03-24',
    last_5_cargoes: 'Grain, Fertilizer, Coal, Grain, Coal',
    owner_manager: 'Unknown Sender',
    vetting_status: null,
    scrubber_fitted: false,
    special_features: null,
    commercial_status: 'Open',
    source: 'teams',
    source_identifier: 'teams-002',
    first_seen_at: '2026-03-24T06:00:00Z',
    last_seen_at: '2026-03-24T06:00:00Z',
    region: 'WCI',
    vessel_type: 'Handymax',
  },
  {
    id: '10',
    vessel_name: 'MV NING YUE HAI',
    dwt: 63562,
    grt: 35600,
    nrt: 21900,
    built_year: 2017,
    flag: 'China',
    loa: 199.9,
    beam: 32.26,
    grain_capacity: 79500,
    crane_details: '4 x 36T cranes',
    speed_laden_knots: 13.5,
    speed_ballast_knots: 14.0,
    consumption_laden_vlsfo: 25.5,
    consumption_ballast_vlsfo: 21.5,
    port_consumption_working_vlsfo: 4.0,
    port_consumption_idle_vlsfo: 1.5,
    open_port: 'Dahej',
    open_date: '2026-03-22',
    last_5_cargoes: 'Coal, Grain, Iron Ore, Coal, Coal',
    owner_manager: 'Unknown Sender',
    vetting_status: 'CDI Inspected',
    scrubber_fitted: true,
    special_features: 'Scrubber fitted',
    commercial_status: 'Open',
    source: 'email',
    source_identifier: 'email-006',
    first_seen_at: '2026-03-22T09:00:00Z',
    last_seen_at: '2026-03-22T09:00:00Z',
    region: 'WCI',
    vessel_type: 'Ultramax',
  },
]
